<?xml version="1.0" encoding="ASCII"?>
<ResourceModel:App xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ResourceModel="http://www.infineon.com/Davex/Resource.ecore" name="ADC_MEASUREMENT" URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0" description="Incorporates analog to digital conversion for the required measurements." mode="NOTSHARABLE" version="4.1.22" minDaveVersion="4.0.0" instanceLabel="ADC_MEASUREMENT_0" appLabel="" containingProxySignal="true">
  <properties singleton="true" provideInit="true"/>
  <virtualSignals name="Channel_A" URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_a" hwSignal="gch" hwResource="//@hwResources.55" visible="true"/>
  <virtualSignals name="Channel_B" URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_b" hwSignal="gch" hwResource="//@hwResources.56" visible="true"/>
  <virtualSignals name="Channel_C" URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_c" hwSignal="gch" hwResource="//@hwResources.57" required="false"/>
  <virtualSignals name="Channel_D" URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_d" hwSignal="gch" hwResource="//@hwResources.58" required="false"/>
  <virtualSignals name="Channel_E" URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_e" hwSignal="gch" hwResource="//@hwResources.59" required="false"/>
  <virtualSignals name="Channel_F" URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_f" hwSignal="gch" hwResource="//@hwResources.60" required="false"/>
  <virtualSignals name="Channel_G" URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_g" hwSignal="gch" hwResource="//@hwResources.61" required="false"/>
  <virtualSignals name="Channel_H" URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_h" hwSignal="gch" hwResource="//@hwResources.62" required="false"/>
  <virtualSignals name="Channel_I" URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_i" hwSignal="gch" hwResource="//@hwResources.63" required="false"/>
  <virtualSignals name="Channel_J" URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_j" hwSignal="gch" hwResource="//@hwResources.64" required="false"/>
  <virtualSignals name="Channel_K" URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_k" hwSignal="gch" hwResource="//@hwResources.65" required="false"/>
  <virtualSignals name="Channel_L" URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_l" hwSignal="gch" hwResource="//@hwResources.66" required="false"/>
  <virtualSignals name="Channel_M" URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_m" hwSignal="gch" hwResource="//@hwResources.67" required="false"/>
  <virtualSignals name="Channel_N" URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_n" hwSignal="gch" hwResource="//@hwResources.68" required="false"/>
  <virtualSignals name="Channel_O" URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_o" hwSignal="gch" hwResource="//@hwResources.69" required="false"/>
  <virtualSignals name="Channel_P" URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_p" hwSignal="gch" hwResource="//@hwResources.70" required="false"/>
  <virtualSignals name="Channel_Q" URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_q" hwSignal="gch" hwResource="//@hwResources.71" required="false"/>
  <virtualSignals name="Channel_R" URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_r" hwSignal="gch" hwResource="//@hwResources.72" required="false"/>
  <virtualSignals name="Channel_S" URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_s" hwSignal="gch" hwResource="//@hwResources.73" required="false"/>
  <virtualSignals name="Channel_T" URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_t" hwSignal="gch" hwResource="//@hwResources.74" required="false"/>
  <virtualSignals name="Channel_U" URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_u" hwSignal="gch" hwResource="//@hwResources.75" required="false"/>
  <virtualSignals name="Channel_V" URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_v" hwSignal="gch" hwResource="//@hwResources.76" required="false"/>
  <virtualSignals name="Channel_W" URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_w" hwSignal="gch" hwResource="//@hwResources.77" required="false"/>
  <virtualSignals name="Channel_X" URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_x" hwSignal="gch" hwResource="//@hwResources.78" required="false"/>
  <virtualSignals name="Channel_Y" URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_y" hwSignal="gch" hwResource="//@hwResources.79" required="false"/>
  <virtualSignals name="Channel_Z" URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_z" hwSignal="gch" hwResource="//@hwResources.80" required="false"/>
  <virtualSignals name="pad_signal_Channel_A" URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_pin_signal_a" hwSignal="pad" hwResource="//@hwResources.3" required="false"/>
  <virtualSignals name="pad_signal_Channel_B" URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_pin_signal_b" hwSignal="pad" hwResource="//@hwResources.4" required="false"/>
  <virtualSignals name="pad_signal_Channel_C" URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_pin_signal_c" hwSignal="pad" hwResource="//@hwResources.5" required="false"/>
  <virtualSignals name="pad_signal_Channel_D" URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_pin_signal_d" hwSignal="pad" hwResource="//@hwResources.6" required="false"/>
  <virtualSignals name="pad_signal_Channel_E" URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_pin_signal_e" hwSignal="pad" hwResource="//@hwResources.7" required="false"/>
  <virtualSignals name="pad_signal_Channel_F" URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_pin_signal_f" hwSignal="pad" hwResource="//@hwResources.8" required="false"/>
  <virtualSignals name="pad_signal_Channel_G" URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_pin_signal_g" hwSignal="pad" hwResource="//@hwResources.9" required="false"/>
  <virtualSignals name="pad_signal_Channel_H" URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_pin_signal_h" hwSignal="pad" hwResource="//@hwResources.10" required="false"/>
  <virtualSignals name="pad_signal_Channel_I" URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_pin_signal_i" hwSignal="pad" hwResource="//@hwResources.11" required="false"/>
  <virtualSignals name="pad_signal_Channel_J" URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_pin_signal_j" hwSignal="pad" hwResource="//@hwResources.12" required="false"/>
  <virtualSignals name="pad_signal_Channel_K" URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_pin_signal_k" hwSignal="pad" hwResource="//@hwResources.13" required="false"/>
  <virtualSignals name="pad_signal_Channel_L" URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_pin_signal_l" hwSignal="pad" hwResource="//@hwResources.14" required="false"/>
  <virtualSignals name="pad_signal_Channel_M" URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_pin_signal_m" hwSignal="pad" hwResource="//@hwResources.15" required="false"/>
  <virtualSignals name="pad_signal_Channel_N" URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_pin_signal_n" hwSignal="pad" hwResource="//@hwResources.16" required="false"/>
  <virtualSignals name="pad_signal_Channel_O" URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_pin_signal_o" hwSignal="pad" hwResource="//@hwResources.17" required="false"/>
  <virtualSignals name="pad_signal_Channel_P" URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_pin_signal_p" hwSignal="pad" hwResource="//@hwResources.18" required="false"/>
  <virtualSignals name="pad_signal_Channel_Q" URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_pin_signal_q" hwSignal="pad" hwResource="//@hwResources.19" required="false"/>
  <virtualSignals name="pad_signal_Channel_R" URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_pin_signal_r" hwSignal="pad" hwResource="//@hwResources.20" required="false"/>
  <virtualSignals name="pad_signal_Channel_S" URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_pin_signal_s" hwSignal="pad" hwResource="//@hwResources.21" required="false"/>
  <virtualSignals name="pad_signal_Channel_T" URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_pin_signal_t" hwSignal="pad" hwResource="//@hwResources.22" required="false"/>
  <virtualSignals name="pad_signal_Channel_U" URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_pin_signal_u" hwSignal="pad" hwResource="//@hwResources.23" required="false"/>
  <virtualSignals name="pad_signal_Channel_V" URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_pin_signal_v" hwSignal="pad" hwResource="//@hwResources.24" required="false"/>
  <virtualSignals name="pad_signal_Channel_W" URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_pin_signal_w" hwSignal="pad" hwResource="//@hwResources.25" required="false"/>
  <virtualSignals name="pad_signal_Channel_X" URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_pin_signal_x" hwSignal="pad" hwResource="//@hwResources.26" required="false"/>
  <virtualSignals name="pad_signal_Channel_Y" URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_pin_signal_y" hwSignal="pad" hwResource="//@hwResources.27" required="false"/>
  <virtualSignals name="pad_signal_Channel_Z" URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_pin_signal_z" hwSignal="pad" hwResource="//@hwResources.28" required="false"/>
  <virtualSignals name="Channel_A_pin_signal" URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_pin_pad_signal_a" hwSignal="pin" hwResource="//@hwResources.29"/>
  <virtualSignals name="Channel_B_pin_signal" URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_pin_pad_signal_b" hwSignal="pin" hwResource="//@hwResources.30"/>
  <virtualSignals name="Channel_C_pin_signal" URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_pin_pad_signal_c" hwSignal="pin" hwResource="//@hwResources.31"/>
  <virtualSignals name="Channel_D_pin_signal" URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_pin_pad_signal_d" hwSignal="pin" hwResource="//@hwResources.32"/>
  <virtualSignals name="Channel_E_pin_signal" URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_pin_pad_signal_e" hwSignal="pin" hwResource="//@hwResources.33"/>
  <virtualSignals name="Channel_F_pin_signal" URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_pin_pad_signal_f" hwSignal="pin" hwResource="//@hwResources.34"/>
  <virtualSignals name="Channel_G_pin_signal" URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_pin_pad_signal_g" hwSignal="pin" hwResource="//@hwResources.35"/>
  <virtualSignals name="Channel_H_pin_signal" URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_pin_pad_signal_h" hwSignal="pin" hwResource="//@hwResources.36"/>
  <virtualSignals name="Channel_I_pin_signal" URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_pin_pad_signal_i" hwSignal="pin" hwResource="//@hwResources.37"/>
  <virtualSignals name="Channel_J_pin_signal" URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_pin_pad_signal_j" hwSignal="pin" hwResource="//@hwResources.38"/>
  <virtualSignals name="Channel_K_pin_signal" URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_pin_pad_signal_k" hwSignal="pin" hwResource="//@hwResources.39"/>
  <virtualSignals name="Channel_L_pin_signal" URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_pin_pad_signal_l" hwSignal="pin" hwResource="//@hwResources.40"/>
  <virtualSignals name="Channel_M_pin_signal" URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_pin_pad_signal_m" hwSignal="pin" hwResource="//@hwResources.41"/>
  <virtualSignals name="Channel_N_pin_signal" URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_pin_pad_signal_n" hwSignal="pin" hwResource="//@hwResources.42"/>
  <virtualSignals name="Channel_O_pin_signal" URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_pin_pad_signal_o" hwSignal="pin" hwResource="//@hwResources.43"/>
  <virtualSignals name="Channel_P_pin_signal" URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_pin_pad_signal_p" hwSignal="pin" hwResource="//@hwResources.44"/>
  <virtualSignals name="Channel_Q_pin_signal" URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_pin_pad_signal_q" hwSignal="pin" hwResource="//@hwResources.45"/>
  <virtualSignals name="Channel_R_pin_signal" URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_pin_pad_signal_r" hwSignal="pin" hwResource="//@hwResources.46"/>
  <virtualSignals name="Channel_S_pin_signal" URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_pin_pad_signal_s" hwSignal="pin" hwResource="//@hwResources.47"/>
  <virtualSignals name="Channel_T_pin_signal" URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_pin_pad_signal_t" hwSignal="pin" hwResource="//@hwResources.48"/>
  <virtualSignals name="Channel_U_pin_signal" URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_pin_pad_signal_u" hwSignal="pin" hwResource="//@hwResources.49"/>
  <virtualSignals name="Channel_V_pin_signal" URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_pin_pad_signal_v" hwSignal="pin" hwResource="//@hwResources.50"/>
  <virtualSignals name="Channel_W_pin_signal" URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_pin_pad_signal_w" hwSignal="pin" hwResource="//@hwResources.51"/>
  <virtualSignals name="Channel_X_pin_signal" URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_pin_pad_signal_x" hwSignal="pin" hwResource="//@hwResources.52"/>
  <virtualSignals name="Channel_Y_pin_signal" URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_pin_pad_signal_y" hwSignal="pin" hwResource="//@hwResources.53"/>
  <virtualSignals name="Channel_Z_pin_signal" URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_pin_pad_signal_z" hwSignal="pin" hwResource="//@hwResources.54"/>
  <virtualSignals name="channel_selectChannel_A" URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_a_select" hwSignal="select" hwResource="//@hwResources.55"/>
  <virtualSignals name="channel_selectChannel_B" URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_b_select" hwSignal="select" hwResource="//@hwResources.56"/>
  <virtualSignals name="channel_selectChannel_C" URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_c_select" hwSignal="select" hwResource="//@hwResources.57" required="false"/>
  <virtualSignals name="channel_selectChannel_D" URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_d_select" hwSignal="select" hwResource="//@hwResources.58" required="false"/>
  <virtualSignals name="channel_selectChannel_E" URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_e_select" hwSignal="select" hwResource="//@hwResources.59" required="false"/>
  <virtualSignals name="channel_selectChannel_F" URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_f_select" hwSignal="select" hwResource="//@hwResources.60" required="false"/>
  <virtualSignals name="channel_selectChannel_G" URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_g_select" hwSignal="select" hwResource="//@hwResources.61" required="false"/>
  <virtualSignals name="channel_selectChannel_H" URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_h_select" hwSignal="select" hwResource="//@hwResources.62" required="false"/>
  <virtualSignals name="channel_selectChannel_I" URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_i_select" hwSignal="select" hwResource="//@hwResources.63" required="false"/>
  <virtualSignals name="channel_selectChannel_J" URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_j_select" hwSignal="select" hwResource="//@hwResources.64" required="false"/>
  <virtualSignals name="channel_selectChannel_K" URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_k_select" hwSignal="select" hwResource="//@hwResources.65" required="false"/>
  <virtualSignals name="channel_selectChannel_L" URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_l_select" hwSignal="select" hwResource="//@hwResources.66" required="false"/>
  <virtualSignals name="channel_selectChannel_M" URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_m_select" hwSignal="select" hwResource="//@hwResources.67" required="false"/>
  <virtualSignals name="channel_selectChannel_N" URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_n_select" hwSignal="select" hwResource="//@hwResources.68" required="false"/>
  <virtualSignals name="channel_selectChannel_O" URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_o_select" hwSignal="select" hwResource="//@hwResources.69" required="false"/>
  <virtualSignals name="channel_selectChannel_P" URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_p_select" hwSignal="select" hwResource="//@hwResources.70" required="false"/>
  <virtualSignals name="channel_selectChannel_Q" URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_q_select" hwSignal="select" hwResource="//@hwResources.71" required="false"/>
  <virtualSignals name="channel_selectChannel_R" URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_r_select" hwSignal="select" hwResource="//@hwResources.72" required="false"/>
  <virtualSignals name="channel_selectChannel_S" URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_s_select" hwSignal="select" hwResource="//@hwResources.73" required="false"/>
  <virtualSignals name="channel_selectChannel_T" URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_t_select" hwSignal="select" hwResource="//@hwResources.74" required="false"/>
  <virtualSignals name="channel_selectChannel_U" URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_u_select" hwSignal="select" hwResource="//@hwResources.75" required="false"/>
  <virtualSignals name="channel_selectChannel_V" URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_v_select" hwSignal="select" hwResource="//@hwResources.76" required="false"/>
  <virtualSignals name="channel_selectChannel_W" URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_w_select" hwSignal="select" hwResource="//@hwResources.77" required="false"/>
  <virtualSignals name="channel_selectChannel_X" URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_x_select" hwSignal="select" hwResource="//@hwResources.78" required="false"/>
  <virtualSignals name="channel_selectChannel_Y" URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_y_select" hwSignal="select" hwResource="//@hwResources.79" required="false"/>
  <virtualSignals name="channel_selectChannel_Z" URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_z_select" hwSignal="select" hwResource="//@hwResources.80" required="false"/>
  <virtualSignals name="event_result" URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_global_res_event" hwSignal="rev0" hwResource="//@hwResources.81" visible="true"/>
  <virtualSignals name="trigger_input" URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_bgreqtrsel" hwSignal="bgreqtrsel" hwResource="//@hwResources.0" visible="true"/>
  <virtualSignals name="gating_input" URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_bgreqgtsel" hwSignal="bgreqgtsel" hwResource="//@hwResources.0" visible="true"/>
  <virtualSignals name="background_connection_to_global_signal" URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_global" hwSignal="global_signal" hwResource="//@hwResources.0" visible="true"/>
  <virtualSignals name="sr_interrupt_signal" URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_signal_src" hwSignal="signal_in" hwResource="//@hwResources.82"/>
  <requiredApps URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/appres_adc_measurement_global_adc" requiredAppName="GLOBAL_ADC" requiringMode="SHARABLE">
    <downwardMapList xsi:type="ResourceModel:App" href="../../GLOBAL_ADC/v4_0_18/GLOBAL_ADC_0.app#/"/>
  </requiredApps>
  <requiredApps URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/appres_adc_measurement_cpu" requiredAppName="CPU_CTRL_XMC1" requiringMode="SHARABLE">
    <downwardMapList xsi:type="ResourceModel:App" href="../../CPU_CTRL_XMC1/v4_0_10/CPU_CTRL_XMC1_0.app#/"/>
  </requiredApps>
  <requiredApps URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/appres_analog_io_channel_a" requiredAppName="ANALOG_IO" requiringMode="SHARABLE">
    <downwardMapList xsi:type="ResourceModel:App" href="../../ANALOG_IO/v4_0_10/ANALOG_IO_0.app#/"/>
  </requiredApps>
  <requiredApps URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/appres_analog_io_channel_b" requiredAppName="ANALOG_IO" requiringMode="SHARABLE">
    <downwardMapList xsi:type="ResourceModel:App" href="../../ANALOG_IO/v4_0_10/ANALOG_IO_1.app#/"/>
  </requiredApps>
  <requiredApps URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/appres_analog_io_channel_c" requiredAppName="ANALOG_IO" required="false" requiringMode="SHARABLE"/>
  <requiredApps URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/appres_analog_io_channel_d" requiredAppName="ANALOG_IO" required="false" requiringMode="SHARABLE"/>
  <requiredApps URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/appres_analog_io_channel_e" requiredAppName="ANALOG_IO" required="false" requiringMode="SHARABLE"/>
  <requiredApps URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/appres_analog_io_channel_f" requiredAppName="ANALOG_IO" required="false" requiringMode="SHARABLE"/>
  <requiredApps URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/appres_analog_io_channel_g" requiredAppName="ANALOG_IO" required="false" requiringMode="SHARABLE"/>
  <requiredApps URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/appres_analog_io_channel_h" requiredAppName="ANALOG_IO" required="false" requiringMode="SHARABLE"/>
  <requiredApps URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/appres_analog_io_channel_i" requiredAppName="ANALOG_IO" required="false" requiringMode="SHARABLE"/>
  <requiredApps URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/appres_analog_io_channel_j" requiredAppName="ANALOG_IO" required="false" requiringMode="SHARABLE"/>
  <requiredApps URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/appres_analog_io_channel_k" requiredAppName="ANALOG_IO" required="false" requiringMode="SHARABLE"/>
  <requiredApps URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/appres_analog_io_channel_l" requiredAppName="ANALOG_IO" required="false" requiringMode="SHARABLE"/>
  <requiredApps URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/appres_analog_io_channel_m" requiredAppName="ANALOG_IO" required="false" requiringMode="SHARABLE"/>
  <requiredApps URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/appres_analog_io_channel_n" requiredAppName="ANALOG_IO" required="false" requiringMode="SHARABLE"/>
  <requiredApps URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/appres_analog_io_channel_o" requiredAppName="ANALOG_IO" required="false" requiringMode="SHARABLE"/>
  <requiredApps URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/appres_analog_io_channel_p" requiredAppName="ANALOG_IO" required="false" requiringMode="SHARABLE"/>
  <requiredApps URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/appres_analog_io_channel_q" requiredAppName="ANALOG_IO" required="false" requiringMode="SHARABLE"/>
  <requiredApps URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/appres_analog_io_channel_r" requiredAppName="ANALOG_IO" required="false" requiringMode="SHARABLE"/>
  <requiredApps URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/appres_analog_io_channel_s" requiredAppName="ANALOG_IO" required="false" requiringMode="SHARABLE"/>
  <requiredApps URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/appres_analog_io_channel_t" requiredAppName="ANALOG_IO" required="false" requiringMode="SHARABLE"/>
  <requiredApps URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/appres_analog_io_channel_u" requiredAppName="ANALOG_IO" required="false" requiringMode="SHARABLE"/>
  <requiredApps URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/appres_analog_io_channel_v" requiredAppName="ANALOG_IO" required="false" requiringMode="SHARABLE"/>
  <requiredApps URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/appres_analog_io_channel_w" requiredAppName="ANALOG_IO" required="false" requiringMode="SHARABLE"/>
  <requiredApps URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/appres_analog_io_channel_x" requiredAppName="ANALOG_IO" required="false" requiringMode="SHARABLE"/>
  <requiredApps URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/appres_analog_io_channel_y" requiredAppName="ANALOG_IO" required="false" requiringMode="SHARABLE"/>
  <requiredApps URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/appres_analog_io_channel_z" requiredAppName="ANALOG_IO" required="false" requiringMode="SHARABLE"/>
  <hwResources name="Background" URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/hwres_adc_measurement_background" resourceGroupUri="peripheral/vadc/*/backgnd" mResGrpUri="peripheral/vadc/*/backgnd">
    <downwardMapList xsi:type="ResourceModel:ResourceGroup" href="../../../HW_RESOURCES/VADC/VADC_0.dd#//@provided.6"/>
  </hwResources>
  <hwResources name="Background class group 1" URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/hwres_adc_measurement_global_iclass" resourceGroupUri="peripheral/vadc/*/class/1" mResGrpUri="peripheral/vadc/*/class/1">
    <downwardMapList xsi:type="ResourceModel:ResourceGroup" href="../../../HW_RESOURCES/VADC/VADC_0.dd#//@provided.0"/>
  </hwResources>
  <hwResources name="Background class group 0" URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/hwres_adc_measurement_global_iclass_xmc11" resourceGroupUri="peripheral/vadc/*/class/0" mResGrpUri="peripheral/vadc/*/class/0">
    <downwardMapList xsi:type="ResourceModel:ResourceGroup" href="../../../HW_RESOURCES/VADC/VADC_0.dd#//@provided.1"/>
  </hwResources>
  <hwResources name="Channel_A_pin" URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/rarray_hwres_adc_measurement_channel_pin#1" resourceGroupUri="" required="false" mResGrpUri="port/p/*/pad/*"/>
  <hwResources name="Channel_B_pin" URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/rarray_hwres_adc_measurement_channel_pin#2" resourceGroupUri="" required="false" mResGrpUri="port/p/*/pad/*"/>
  <hwResources name="Channel_C_pin" URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/rarray_hwres_adc_measurement_channel_pin#3" resourceGroupUri="" required="false" mResGrpUri="port/p/*/pad/*"/>
  <hwResources name="Channel_D_pin" URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/rarray_hwres_adc_measurement_channel_pin#4" resourceGroupUri="" required="false" mResGrpUri="port/p/*/pad/*"/>
  <hwResources name="Channel_E_pin" URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/rarray_hwres_adc_measurement_channel_pin#5" resourceGroupUri="" required="false" mResGrpUri="port/p/*/pad/*"/>
  <hwResources name="Channel_F_pin" URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/rarray_hwres_adc_measurement_channel_pin#6" resourceGroupUri="" required="false" mResGrpUri="port/p/*/pad/*"/>
  <hwResources name="Channel_G_pin" URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/rarray_hwres_adc_measurement_channel_pin#7" resourceGroupUri="" required="false" mResGrpUri="port/p/*/pad/*"/>
  <hwResources name="Channel_H_pin" URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/rarray_hwres_adc_measurement_channel_pin#8" resourceGroupUri="" required="false" mResGrpUri="port/p/*/pad/*"/>
  <hwResources name="Channel_I_pin" URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/rarray_hwres_adc_measurement_channel_pin#9" resourceGroupUri="" required="false" mResGrpUri="port/p/*/pad/*"/>
  <hwResources name="Channel_J_pin" URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/rarray_hwres_adc_measurement_channel_pin#10" resourceGroupUri="" required="false" mResGrpUri="port/p/*/pad/*"/>
  <hwResources name="Channel_K_pin" URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/rarray_hwres_adc_measurement_channel_pin#11" resourceGroupUri="" required="false" mResGrpUri="port/p/*/pad/*"/>
  <hwResources name="Channel_L_pin" URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/rarray_hwres_adc_measurement_channel_pin#12" resourceGroupUri="" required="false" mResGrpUri="port/p/*/pad/*"/>
  <hwResources name="Channel_M_pin" URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/rarray_hwres_adc_measurement_channel_pin#13" resourceGroupUri="" required="false" mResGrpUri="port/p/*/pad/*"/>
  <hwResources name="Channel_N_pin" URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/rarray_hwres_adc_measurement_channel_pin#14" resourceGroupUri="" required="false" mResGrpUri="port/p/*/pad/*"/>
  <hwResources name="Channel_O_pin" URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/rarray_hwres_adc_measurement_channel_pin#15" resourceGroupUri="" required="false" mResGrpUri="port/p/*/pad/*"/>
  <hwResources name="Channel_P_pin" URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/rarray_hwres_adc_measurement_channel_pin#16" resourceGroupUri="" required="false" mResGrpUri="port/p/*/pad/*"/>
  <hwResources name="Channel_Q_pin" URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/rarray_hwres_adc_measurement_channel_pin#17" resourceGroupUri="" required="false" mResGrpUri="port/p/*/pad/*"/>
  <hwResources name="Channel_R_pin" URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/rarray_hwres_adc_measurement_channel_pin#18" resourceGroupUri="" required="false" mResGrpUri="port/p/*/pad/*"/>
  <hwResources name="Channel_S_pin" URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/rarray_hwres_adc_measurement_channel_pin#19" resourceGroupUri="" required="false" mResGrpUri="port/p/*/pad/*"/>
  <hwResources name="Channel_T_pin" URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/rarray_hwres_adc_measurement_channel_pin#20" resourceGroupUri="" required="false" mResGrpUri="port/p/*/pad/*"/>
  <hwResources name="Channel_U_pin" URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/rarray_hwres_adc_measurement_channel_pin#21" resourceGroupUri="" required="false" mResGrpUri="port/p/*/pad/*"/>
  <hwResources name="Channel_V_pin" URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/rarray_hwres_adc_measurement_channel_pin#22" resourceGroupUri="" required="false" mResGrpUri="port/p/*/pad/*"/>
  <hwResources name="Channel_W_pin" URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/rarray_hwres_adc_measurement_channel_pin#23" resourceGroupUri="" required="false" mResGrpUri="port/p/*/pad/*"/>
  <hwResources name="Channel_X_pin" URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/rarray_hwres_adc_measurement_channel_pin#24" resourceGroupUri="" required="false" mResGrpUri="port/p/*/pad/*"/>
  <hwResources name="Channel_Y_pin" URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/rarray_hwres_adc_measurement_channel_pin#25" resourceGroupUri="" required="false" mResGrpUri="port/p/*/pad/*"/>
  <hwResources name="Channel_Z_pin" URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/rarray_hwres_adc_measurement_channel_pin#26" resourceGroupUri="" required="false" mResGrpUri="port/p/*/pad/*"/>
  <hwResources name="pin_Channel_A" URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/rarray_hwres_adc_measurement_pin_pad#1" resourceGroupUri="" required="false" mResGrpUri="devicepackage/0/*"/>
  <hwResources name="pin_Channel_B" URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/rarray_hwres_adc_measurement_pin_pad#2" resourceGroupUri="" required="false" mResGrpUri="devicepackage/0/*"/>
  <hwResources name="pin_Channel_C" URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/rarray_hwres_adc_measurement_pin_pad#3" resourceGroupUri="" required="false" mResGrpUri="devicepackage/0/*"/>
  <hwResources name="pin_Channel_D" URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/rarray_hwres_adc_measurement_pin_pad#4" resourceGroupUri="" required="false" mResGrpUri="devicepackage/0/*"/>
  <hwResources name="pin_Channel_E" URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/rarray_hwres_adc_measurement_pin_pad#5" resourceGroupUri="" required="false" mResGrpUri="devicepackage/0/*"/>
  <hwResources name="pin_Channel_F" URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/rarray_hwres_adc_measurement_pin_pad#6" resourceGroupUri="" required="false" mResGrpUri="devicepackage/0/*"/>
  <hwResources name="pin_Channel_G" URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/rarray_hwres_adc_measurement_pin_pad#7" resourceGroupUri="" required="false" mResGrpUri="devicepackage/0/*"/>
  <hwResources name="pin_Channel_H" URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/rarray_hwres_adc_measurement_pin_pad#8" resourceGroupUri="" required="false" mResGrpUri="devicepackage/0/*"/>
  <hwResources name="pin_Channel_I" URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/rarray_hwres_adc_measurement_pin_pad#9" resourceGroupUri="" required="false" mResGrpUri="devicepackage/0/*"/>
  <hwResources name="pin_Channel_J" URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/rarray_hwres_adc_measurement_pin_pad#10" resourceGroupUri="" required="false" mResGrpUri="devicepackage/0/*"/>
  <hwResources name="pin_Channel_K" URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/rarray_hwres_adc_measurement_pin_pad#11" resourceGroupUri="" required="false" mResGrpUri="devicepackage/0/*"/>
  <hwResources name="pin_Channel_L" URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/rarray_hwres_adc_measurement_pin_pad#12" resourceGroupUri="" required="false" mResGrpUri="devicepackage/0/*"/>
  <hwResources name="pin_Channel_M" URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/rarray_hwres_adc_measurement_pin_pad#13" resourceGroupUri="" required="false" mResGrpUri="devicepackage/0/*"/>
  <hwResources name="pin_Channel_N" URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/rarray_hwres_adc_measurement_pin_pad#14" resourceGroupUri="" required="false" mResGrpUri="devicepackage/0/*"/>
  <hwResources name="pin_Channel_O" URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/rarray_hwres_adc_measurement_pin_pad#15" resourceGroupUri="" required="false" mResGrpUri="devicepackage/0/*"/>
  <hwResources name="pin_Channel_P" URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/rarray_hwres_adc_measurement_pin_pad#16" resourceGroupUri="" required="false" mResGrpUri="devicepackage/0/*"/>
  <hwResources name="pin_Channel_Q" URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/rarray_hwres_adc_measurement_pin_pad#17" resourceGroupUri="" required="false" mResGrpUri="devicepackage/0/*"/>
  <hwResources name="pin_Channel_R" URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/rarray_hwres_adc_measurement_pin_pad#18" resourceGroupUri="" required="false" mResGrpUri="devicepackage/0/*"/>
  <hwResources name="pin_Channel_S" URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/rarray_hwres_adc_measurement_pin_pad#19" resourceGroupUri="" required="false" mResGrpUri="devicepackage/0/*"/>
  <hwResources name="pin_Channel_T" URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/rarray_hwres_adc_measurement_pin_pad#20" resourceGroupUri="" required="false" mResGrpUri="devicepackage/0/*"/>
  <hwResources name="pin_Channel_U" URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/rarray_hwres_adc_measurement_pin_pad#21" resourceGroupUri="" required="false" mResGrpUri="devicepackage/0/*"/>
  <hwResources name="pin_Channel_V" URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/rarray_hwres_adc_measurement_pin_pad#22" resourceGroupUri="" required="false" mResGrpUri="devicepackage/0/*"/>
  <hwResources name="pin_Channel_W" URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/rarray_hwres_adc_measurement_pin_pad#23" resourceGroupUri="" required="false" mResGrpUri="devicepackage/0/*"/>
  <hwResources name="pin_Channel_X" URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/rarray_hwres_adc_measurement_pin_pad#24" resourceGroupUri="" required="false" mResGrpUri="devicepackage/0/*"/>
  <hwResources name="pin_Channel_Y" URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/rarray_hwres_adc_measurement_pin_pad#25" resourceGroupUri="" required="false" mResGrpUri="devicepackage/0/*"/>
  <hwResources name="pin_Channel_Z" URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/rarray_hwres_adc_measurement_pin_pad#26" resourceGroupUri="" required="false" mResGrpUri="devicepackage/0/*"/>
  <hwResources name="Channel_A" URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/rarray_hwres_adc_measurement_channels#1" resourceGroupUri="peripheral/vadc/0/group/*/ch/*" mResGrpUri="peripheral/vadc/0/group/*/ch/*">
    <downwardMapList xsi:type="ResourceModel:ResourceGroup" href="../../../HW_RESOURCES/VADC/VADC_0.dd#//@provided.16"/>
  </hwResources>
  <hwResources name="Channel_B" URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/rarray_hwres_adc_measurement_channels#2" resourceGroupUri="peripheral/vadc/0/group/*/ch/*" mResGrpUri="peripheral/vadc/0/group/*/ch/*">
    <downwardMapList xsi:type="ResourceModel:ResourceGroup" href="../../../HW_RESOURCES/VADC/VADC_0.dd#//@provided.17"/>
  </hwResources>
  <hwResources name="Channel_C" URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/rarray_hwres_adc_measurement_channels#3" resourceGroupUri="" required="false" mResGrpUri="peripheral/vadc/0/group/*/ch/*"/>
  <hwResources name="Channel_D" URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/rarray_hwres_adc_measurement_channels#4" resourceGroupUri="" required="false" mResGrpUri="peripheral/vadc/0/group/*/ch/*"/>
  <hwResources name="Channel_E" URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/rarray_hwres_adc_measurement_channels#5" resourceGroupUri="" required="false" mResGrpUri="peripheral/vadc/0/group/*/ch/*"/>
  <hwResources name="Channel_F" URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/rarray_hwres_adc_measurement_channels#6" resourceGroupUri="" required="false" mResGrpUri="peripheral/vadc/0/group/*/ch/*"/>
  <hwResources name="Channel_G" URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/rarray_hwres_adc_measurement_channels#7" resourceGroupUri="" required="false" mResGrpUri="peripheral/vadc/0/group/*/ch/*"/>
  <hwResources name="Channel_H" URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/rarray_hwres_adc_measurement_channels#8" resourceGroupUri="" required="false" mResGrpUri="peripheral/vadc/0/group/*/ch/*"/>
  <hwResources name="Channel_I" URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/rarray_hwres_adc_measurement_channels#9" resourceGroupUri="" required="false" mResGrpUri="peripheral/vadc/0/group/*/ch/*"/>
  <hwResources name="Channel_J" URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/rarray_hwres_adc_measurement_channels#10" resourceGroupUri="" required="false" mResGrpUri="peripheral/vadc/0/group/*/ch/*"/>
  <hwResources name="Channel_K" URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/rarray_hwres_adc_measurement_channels#11" resourceGroupUri="" required="false" mResGrpUri="peripheral/vadc/0/group/*/ch/*"/>
  <hwResources name="Channel_L" URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/rarray_hwres_adc_measurement_channels#12" resourceGroupUri="" required="false" mResGrpUri="peripheral/vadc/0/group/*/ch/*"/>
  <hwResources name="Channel_M" URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/rarray_hwres_adc_measurement_channels#13" resourceGroupUri="" required="false" mResGrpUri="peripheral/vadc/0/group/*/ch/*"/>
  <hwResources name="Channel_N" URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/rarray_hwres_adc_measurement_channels#14" resourceGroupUri="" required="false" mResGrpUri="peripheral/vadc/0/group/*/ch/*"/>
  <hwResources name="Channel_O" URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/rarray_hwres_adc_measurement_channels#15" resourceGroupUri="" required="false" mResGrpUri="peripheral/vadc/0/group/*/ch/*"/>
  <hwResources name="Channel_P" URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/rarray_hwres_adc_measurement_channels#16" resourceGroupUri="" required="false" mResGrpUri="peripheral/vadc/0/group/*/ch/*"/>
  <hwResources name="Channel_Q" URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/rarray_hwres_adc_measurement_channels#17" resourceGroupUri="" required="false" mResGrpUri="peripheral/vadc/0/group/*/ch/*"/>
  <hwResources name="Channel_R" URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/rarray_hwres_adc_measurement_channels#18" resourceGroupUri="" required="false" mResGrpUri="peripheral/vadc/0/group/*/ch/*"/>
  <hwResources name="Channel_S" URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/rarray_hwres_adc_measurement_channels#19" resourceGroupUri="" required="false" mResGrpUri="peripheral/vadc/0/group/*/ch/*"/>
  <hwResources name="Channel_T" URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/rarray_hwres_adc_measurement_channels#20" resourceGroupUri="" required="false" mResGrpUri="peripheral/vadc/0/group/*/ch/*"/>
  <hwResources name="Channel_U" URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/rarray_hwres_adc_measurement_channels#21" resourceGroupUri="" required="false" mResGrpUri="peripheral/vadc/0/group/*/ch/*"/>
  <hwResources name="Channel_V" URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/rarray_hwres_adc_measurement_channels#22" resourceGroupUri="" required="false" mResGrpUri="peripheral/vadc/0/group/*/ch/*"/>
  <hwResources name="Channel_W" URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/rarray_hwres_adc_measurement_channels#23" resourceGroupUri="" required="false" mResGrpUri="peripheral/vadc/0/group/*/ch/*"/>
  <hwResources name="Channel_X" URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/rarray_hwres_adc_measurement_channels#24" resourceGroupUri="" required="false" mResGrpUri="peripheral/vadc/0/group/*/ch/*"/>
  <hwResources name="Channel_Y" URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/rarray_hwres_adc_measurement_channels#25" resourceGroupUri="" required="false" mResGrpUri="peripheral/vadc/0/group/*/ch/*"/>
  <hwResources name="Channel_Z" URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/rarray_hwres_adc_measurement_channels#26" resourceGroupUri="" required="false" mResGrpUri="peripheral/vadc/0/group/*/ch/*"/>
  <hwResources name="Global Result Register" URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/hwres_adc_measurement_vadc_global_result" resourceGroupUri="peripheral/vadc/*/global_result" mResGrpUri="peripheral/vadc/*/global_result">
    <downwardMapList xsi:type="ResourceModel:ResourceGroup" href="../../../HW_RESOURCES/VADC/VADC_0.dd#//@provided.3"/>
  </hwResources>
  <hwResources name="Global Result Interrupt" URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/hwres_adc_measurement_nvicnode_srcevt" resourceGroupUri="peripheral/cpu/0/nvic/interrupt/*" mResGrpUri="peripheral/cpu/0/nvic/interrupt/*">
    <downwardMapList xsi:type="ResourceModel:ResourceGroup" href="../../../HW_RESOURCES/CPU/CPU_0.dd#//@provided.1"/>
  </hwResources>
  <connections URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_pin_signal_a/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_pin_pad_signal_a" systemDefined="true" sourceSignal="pad_signal_Channel_A" targetSignal="Channel_A_pin_signal" srcVirtualSignal="//@virtualSignals.26" targetVirtualSignal="//@virtualSignals.52"/>
  <connections URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_pin_pad_signal_a/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_pin_signal_a" systemDefined="true" sourceSignal="Channel_A_pin_signal" targetSignal="pad_signal_Channel_A" srcVirtualSignal="//@virtualSignals.52" targetVirtualSignal="//@virtualSignals.26"/>
  <connections URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_pin_signal_b/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_pin_pad_signal_b" systemDefined="true" sourceSignal="pad_signal_Channel_B" targetSignal="Channel_B_pin_signal" srcVirtualSignal="//@virtualSignals.27" targetVirtualSignal="//@virtualSignals.53"/>
  <connections URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_pin_pad_signal_b/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_pin_signal_b" systemDefined="true" sourceSignal="Channel_B_pin_signal" targetSignal="pad_signal_Channel_B" srcVirtualSignal="//@virtualSignals.53" targetVirtualSignal="//@virtualSignals.27"/>
  <connections URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_pin_signal_c/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_pin_pad_signal_c" systemDefined="true" sourceSignal="pad_signal_Channel_C" targetSignal="Channel_C_pin_signal" srcVirtualSignal="//@virtualSignals.28" targetVirtualSignal="//@virtualSignals.54"/>
  <connections URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_pin_pad_signal_c/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_pin_signal_c" systemDefined="true" sourceSignal="Channel_C_pin_signal" targetSignal="pad_signal_Channel_C" srcVirtualSignal="//@virtualSignals.54" targetVirtualSignal="//@virtualSignals.28"/>
  <connections URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_pin_signal_d/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_pin_pad_signal_d" systemDefined="true" sourceSignal="pad_signal_Channel_D" targetSignal="Channel_D_pin_signal" srcVirtualSignal="//@virtualSignals.29" targetVirtualSignal="//@virtualSignals.55"/>
  <connections URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_pin_pad_signal_d/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_pin_signal_d" systemDefined="true" sourceSignal="Channel_D_pin_signal" targetSignal="pad_signal_Channel_D" srcVirtualSignal="//@virtualSignals.55" targetVirtualSignal="//@virtualSignals.29"/>
  <connections URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_pin_signal_e/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_pin_pad_signal_e" systemDefined="true" sourceSignal="pad_signal_Channel_E" targetSignal="Channel_E_pin_signal" srcVirtualSignal="//@virtualSignals.30" targetVirtualSignal="//@virtualSignals.56"/>
  <connections URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_pin_pad_signal_e/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_pin_signal_e" systemDefined="true" sourceSignal="Channel_E_pin_signal" targetSignal="pad_signal_Channel_E" srcVirtualSignal="//@virtualSignals.56" targetVirtualSignal="//@virtualSignals.30"/>
  <connections URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_pin_signal_f/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_pin_pad_signal_f" systemDefined="true" sourceSignal="pad_signal_Channel_F" targetSignal="Channel_F_pin_signal" srcVirtualSignal="//@virtualSignals.31" targetVirtualSignal="//@virtualSignals.57"/>
  <connections URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_pin_pad_signal_f/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_pin_signal_f" systemDefined="true" sourceSignal="Channel_F_pin_signal" targetSignal="pad_signal_Channel_F" srcVirtualSignal="//@virtualSignals.57" targetVirtualSignal="//@virtualSignals.31"/>
  <connections URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_pin_signal_g/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_pin_pad_signal_g" systemDefined="true" sourceSignal="pad_signal_Channel_G" targetSignal="Channel_G_pin_signal" srcVirtualSignal="//@virtualSignals.32" targetVirtualSignal="//@virtualSignals.58"/>
  <connections URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_pin_pad_signal_g/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_pin_signal_g" systemDefined="true" sourceSignal="Channel_G_pin_signal" targetSignal="pad_signal_Channel_G" srcVirtualSignal="//@virtualSignals.58" targetVirtualSignal="//@virtualSignals.32"/>
  <connections URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_pin_signal_h/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_pin_pad_signal_h" systemDefined="true" sourceSignal="pad_signal_Channel_H" targetSignal="Channel_H_pin_signal" srcVirtualSignal="//@virtualSignals.33" targetVirtualSignal="//@virtualSignals.59"/>
  <connections URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_pin_pad_signal_h/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_pin_signal_h" systemDefined="true" sourceSignal="Channel_H_pin_signal" targetSignal="pad_signal_Channel_H" srcVirtualSignal="//@virtualSignals.59" targetVirtualSignal="//@virtualSignals.33"/>
  <connections URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_pin_signal_i/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_pin_pad_signal_i" systemDefined="true" sourceSignal="pad_signal_Channel_I" targetSignal="Channel_I_pin_signal" srcVirtualSignal="//@virtualSignals.34" targetVirtualSignal="//@virtualSignals.60"/>
  <connections URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_pin_pad_signal_i/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_pin_signal_i" systemDefined="true" sourceSignal="Channel_I_pin_signal" targetSignal="pad_signal_Channel_I" srcVirtualSignal="//@virtualSignals.60" targetVirtualSignal="//@virtualSignals.34"/>
  <connections URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_pin_signal_j/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_pin_pad_signal_j" systemDefined="true" sourceSignal="pad_signal_Channel_J" targetSignal="Channel_J_pin_signal" srcVirtualSignal="//@virtualSignals.35" targetVirtualSignal="//@virtualSignals.61"/>
  <connections URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_pin_pad_signal_j/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_pin_signal_j" systemDefined="true" sourceSignal="Channel_J_pin_signal" targetSignal="pad_signal_Channel_J" srcVirtualSignal="//@virtualSignals.61" targetVirtualSignal="//@virtualSignals.35"/>
  <connections URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_pin_signal_k/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_pin_pad_signal_k" systemDefined="true" sourceSignal="pad_signal_Channel_K" targetSignal="Channel_K_pin_signal" srcVirtualSignal="//@virtualSignals.36" targetVirtualSignal="//@virtualSignals.62"/>
  <connections URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_pin_pad_signal_k/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_pin_signal_k" systemDefined="true" sourceSignal="Channel_K_pin_signal" targetSignal="pad_signal_Channel_K" srcVirtualSignal="//@virtualSignals.62" targetVirtualSignal="//@virtualSignals.36"/>
  <connections URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_pin_signal_l/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_pin_pad_signal_l" systemDefined="true" sourceSignal="pad_signal_Channel_L" targetSignal="Channel_L_pin_signal" srcVirtualSignal="//@virtualSignals.37" targetVirtualSignal="//@virtualSignals.63"/>
  <connections URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_pin_pad_signal_l/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_pin_signal_l" systemDefined="true" sourceSignal="Channel_L_pin_signal" targetSignal="pad_signal_Channel_L" srcVirtualSignal="//@virtualSignals.63" targetVirtualSignal="//@virtualSignals.37"/>
  <connections URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_pin_signal_m/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_pin_pad_signal_m" systemDefined="true" sourceSignal="pad_signal_Channel_M" targetSignal="Channel_M_pin_signal" srcVirtualSignal="//@virtualSignals.38" targetVirtualSignal="//@virtualSignals.64"/>
  <connections URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_pin_pad_signal_m/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_pin_signal_m" systemDefined="true" sourceSignal="Channel_M_pin_signal" targetSignal="pad_signal_Channel_M" srcVirtualSignal="//@virtualSignals.64" targetVirtualSignal="//@virtualSignals.38"/>
  <connections URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_pin_signal_n/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_pin_pad_signal_n" systemDefined="true" sourceSignal="pad_signal_Channel_N" targetSignal="Channel_N_pin_signal" srcVirtualSignal="//@virtualSignals.39" targetVirtualSignal="//@virtualSignals.65"/>
  <connections URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_pin_pad_signal_n/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_pin_signal_n" systemDefined="true" sourceSignal="Channel_N_pin_signal" targetSignal="pad_signal_Channel_N" srcVirtualSignal="//@virtualSignals.65" targetVirtualSignal="//@virtualSignals.39"/>
  <connections URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_pin_signal_o/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_pin_pad_signal_o" systemDefined="true" sourceSignal="pad_signal_Channel_O" targetSignal="Channel_O_pin_signal" srcVirtualSignal="//@virtualSignals.40" targetVirtualSignal="//@virtualSignals.66"/>
  <connections URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_pin_pad_signal_o/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_pin_signal_o" systemDefined="true" sourceSignal="Channel_O_pin_signal" targetSignal="pad_signal_Channel_O" srcVirtualSignal="//@virtualSignals.66" targetVirtualSignal="//@virtualSignals.40"/>
  <connections URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_pin_signal_p/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_pin_pad_signal_p" systemDefined="true" sourceSignal="pad_signal_Channel_P" targetSignal="Channel_P_pin_signal" srcVirtualSignal="//@virtualSignals.41" targetVirtualSignal="//@virtualSignals.67"/>
  <connections URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_pin_pad_signal_p/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_pin_signal_p" systemDefined="true" sourceSignal="Channel_P_pin_signal" targetSignal="pad_signal_Channel_P" srcVirtualSignal="//@virtualSignals.67" targetVirtualSignal="//@virtualSignals.41"/>
  <connections URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_pin_signal_q/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_pin_pad_signal_q" systemDefined="true" sourceSignal="pad_signal_Channel_Q" targetSignal="Channel_Q_pin_signal" srcVirtualSignal="//@virtualSignals.42" targetVirtualSignal="//@virtualSignals.68"/>
  <connections URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_pin_pad_signal_q/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_pin_signal_q" systemDefined="true" sourceSignal="Channel_Q_pin_signal" targetSignal="pad_signal_Channel_Q" srcVirtualSignal="//@virtualSignals.68" targetVirtualSignal="//@virtualSignals.42"/>
  <connections URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_pin_signal_r/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_pin_pad_signal_r" systemDefined="true" sourceSignal="pad_signal_Channel_R" targetSignal="Channel_R_pin_signal" srcVirtualSignal="//@virtualSignals.43" targetVirtualSignal="//@virtualSignals.69"/>
  <connections URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_pin_pad_signal_r/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_pin_signal_r" systemDefined="true" sourceSignal="Channel_R_pin_signal" targetSignal="pad_signal_Channel_R" srcVirtualSignal="//@virtualSignals.69" targetVirtualSignal="//@virtualSignals.43"/>
  <connections URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_pin_signal_s/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_pin_pad_signal_s" systemDefined="true" sourceSignal="pad_signal_Channel_S" targetSignal="Channel_S_pin_signal" srcVirtualSignal="//@virtualSignals.44" targetVirtualSignal="//@virtualSignals.70"/>
  <connections URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_pin_pad_signal_s/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_pin_signal_s" systemDefined="true" sourceSignal="Channel_S_pin_signal" targetSignal="pad_signal_Channel_S" srcVirtualSignal="//@virtualSignals.70" targetVirtualSignal="//@virtualSignals.44"/>
  <connections URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_pin_signal_t/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_pin_pad_signal_t" systemDefined="true" sourceSignal="pad_signal_Channel_T" targetSignal="Channel_T_pin_signal" srcVirtualSignal="//@virtualSignals.45" targetVirtualSignal="//@virtualSignals.71"/>
  <connections URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_pin_pad_signal_t/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_pin_signal_t" systemDefined="true" sourceSignal="Channel_T_pin_signal" targetSignal="pad_signal_Channel_T" srcVirtualSignal="//@virtualSignals.71" targetVirtualSignal="//@virtualSignals.45"/>
  <connections URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_pin_signal_u/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_pin_pad_signal_u" systemDefined="true" sourceSignal="pad_signal_Channel_U" targetSignal="Channel_U_pin_signal" srcVirtualSignal="//@virtualSignals.46" targetVirtualSignal="//@virtualSignals.72"/>
  <connections URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_pin_pad_signal_u/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_pin_signal_u" systemDefined="true" sourceSignal="Channel_U_pin_signal" targetSignal="pad_signal_Channel_U" srcVirtualSignal="//@virtualSignals.72" targetVirtualSignal="//@virtualSignals.46"/>
  <connections URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_pin_signal_v/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_pin_pad_signal_v" systemDefined="true" sourceSignal="pad_signal_Channel_V" targetSignal="Channel_V_pin_signal" srcVirtualSignal="//@virtualSignals.47" targetVirtualSignal="//@virtualSignals.73"/>
  <connections URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_pin_pad_signal_v/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_pin_signal_v" systemDefined="true" sourceSignal="Channel_V_pin_signal" targetSignal="pad_signal_Channel_V" srcVirtualSignal="//@virtualSignals.73" targetVirtualSignal="//@virtualSignals.47"/>
  <connections URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_pin_signal_w/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_pin_pad_signal_w" systemDefined="true" sourceSignal="pad_signal_Channel_W" targetSignal="Channel_W_pin_signal" srcVirtualSignal="//@virtualSignals.48" targetVirtualSignal="//@virtualSignals.74"/>
  <connections URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_pin_pad_signal_w/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_pin_signal_w" systemDefined="true" sourceSignal="Channel_W_pin_signal" targetSignal="pad_signal_Channel_W" srcVirtualSignal="//@virtualSignals.74" targetVirtualSignal="//@virtualSignals.48"/>
  <connections URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_pin_signal_x/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_pin_pad_signal_x" systemDefined="true" sourceSignal="pad_signal_Channel_X" targetSignal="Channel_X_pin_signal" srcVirtualSignal="//@virtualSignals.49" targetVirtualSignal="//@virtualSignals.75"/>
  <connections URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_pin_pad_signal_x/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_pin_signal_x" systemDefined="true" sourceSignal="Channel_X_pin_signal" targetSignal="pad_signal_Channel_X" srcVirtualSignal="//@virtualSignals.75" targetVirtualSignal="//@virtualSignals.49"/>
  <connections URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_pin_signal_y/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_pin_pad_signal_y" systemDefined="true" sourceSignal="pad_signal_Channel_Y" targetSignal="Channel_Y_pin_signal" srcVirtualSignal="//@virtualSignals.50" targetVirtualSignal="//@virtualSignals.76"/>
  <connections URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_pin_pad_signal_y/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_pin_signal_y" systemDefined="true" sourceSignal="Channel_Y_pin_signal" targetSignal="pad_signal_Channel_Y" srcVirtualSignal="//@virtualSignals.76" targetVirtualSignal="//@virtualSignals.50"/>
  <connections URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_pin_signal_z/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_pin_pad_signal_z" systemDefined="true" sourceSignal="pad_signal_Channel_Z" targetSignal="Channel_Z_pin_signal" srcVirtualSignal="//@virtualSignals.51" targetVirtualSignal="//@virtualSignals.77"/>
  <connections URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_pin_pad_signal_z/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_pin_signal_z" systemDefined="true" sourceSignal="Channel_Z_pin_signal" targetSignal="pad_signal_Channel_Z" srcVirtualSignal="//@virtualSignals.77" targetVirtualSignal="//@virtualSignals.51"/>
  <connections URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_global_res_event/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_signal_src" systemDefined="true" sourceSignal="event_result" targetSignal="sr_interrupt_signal" srcVirtualSignal="//@virtualSignals.104" targetVirtualSignal="//@virtualSignals.108"/>
  <connections URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_global_adc_global_signal/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_global" systemDefined="true" sourceSignal="global_signal" targetSignal="background_connection_to_global_signal" targetVirtualSignal="//@virtualSignals.107" proxySrcVirtualSignalUri="http://resources/4.0.18/app/GLOBAL_ADC/0/vs_global_adc_global" containingProxySignal="true">
    <downwardMapList xsi:type="ResourceModel:VirtualSignal" href="../../GLOBAL_ADC/v4_0_18/GLOBAL_ADC_0.app#//@virtualSignals.0"/>
    <srcVirtualSignal href="../../GLOBAL_ADC/v4_0_18/GLOBAL_ADC_0.app#//@virtualSignals.0"/>
  </connections>
  <connections URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_pin_signal_a/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_a" systemDefined="true" sourceSignal="pad_signal_Channel_A" targetSignal="Channel_A" required="false" srcVirtualSignal="//@virtualSignals.26" targetVirtualSignal="//@virtualSignals.0"/>
  <connections URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_pin_signal_b/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_b" systemDefined="true" sourceSignal="pad_signal_Channel_B" targetSignal="Channel_B" required="false" srcVirtualSignal="//@virtualSignals.27" targetVirtualSignal="//@virtualSignals.1"/>
  <connections URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_pin_signal_c/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_c" systemDefined="true" sourceSignal="pad_signal_Channel_C" targetSignal="Channel_C" required="false" srcVirtualSignal="//@virtualSignals.28" targetVirtualSignal="//@virtualSignals.2"/>
  <connections URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_pin_signal_d/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_d" systemDefined="true" sourceSignal="pad_signal_Channel_D" targetSignal="Channel_D" required="false" srcVirtualSignal="//@virtualSignals.29" targetVirtualSignal="//@virtualSignals.3"/>
  <connections URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_pin_signal_e/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_e" systemDefined="true" sourceSignal="pad_signal_Channel_E" targetSignal="Channel_E" required="false" srcVirtualSignal="//@virtualSignals.30" targetVirtualSignal="//@virtualSignals.4"/>
  <connections URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_pin_signal_f/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_f" systemDefined="true" sourceSignal="pad_signal_Channel_F" targetSignal="Channel_F" required="false" srcVirtualSignal="//@virtualSignals.31" targetVirtualSignal="//@virtualSignals.5"/>
  <connections URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_pin_signal_g/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_g" systemDefined="true" sourceSignal="pad_signal_Channel_G" targetSignal="Channel_G" required="false" srcVirtualSignal="//@virtualSignals.32" targetVirtualSignal="//@virtualSignals.6"/>
  <connections URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_pin_signal_h/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_h" systemDefined="true" sourceSignal="pad_signal_Channel_H" targetSignal="Channel_H" required="false" srcVirtualSignal="//@virtualSignals.33" targetVirtualSignal="//@virtualSignals.7"/>
  <connections URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_pin_signal_i/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_i" systemDefined="true" sourceSignal="pad_signal_Channel_I" targetSignal="Channel_I" required="false" srcVirtualSignal="//@virtualSignals.34" targetVirtualSignal="//@virtualSignals.8"/>
  <connections URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_pin_signal_j/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_j" systemDefined="true" sourceSignal="pad_signal_Channel_J" targetSignal="Channel_J" required="false" srcVirtualSignal="//@virtualSignals.35" targetVirtualSignal="//@virtualSignals.9"/>
  <connections URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_pin_signal_k/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_k" systemDefined="true" sourceSignal="pad_signal_Channel_K" targetSignal="Channel_K" required="false" srcVirtualSignal="//@virtualSignals.36" targetVirtualSignal="//@virtualSignals.10"/>
  <connections URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_pin_signal_l/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_l" systemDefined="true" sourceSignal="pad_signal_Channel_L" targetSignal="Channel_L" required="false" srcVirtualSignal="//@virtualSignals.37" targetVirtualSignal="//@virtualSignals.11"/>
  <connections URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_pin_signal_m/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_m" systemDefined="true" sourceSignal="pad_signal_Channel_M" targetSignal="Channel_M" required="false" srcVirtualSignal="//@virtualSignals.38" targetVirtualSignal="//@virtualSignals.12"/>
  <connections URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_pin_signal_n/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_n" systemDefined="true" sourceSignal="pad_signal_Channel_N" targetSignal="Channel_N" required="false" srcVirtualSignal="//@virtualSignals.39" targetVirtualSignal="//@virtualSignals.13"/>
  <connections URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_pin_signal_o/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_o" systemDefined="true" sourceSignal="pad_signal_Channel_O" targetSignal="Channel_O" required="false" srcVirtualSignal="//@virtualSignals.40" targetVirtualSignal="//@virtualSignals.14"/>
  <connections URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_pin_signal_p/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_p" systemDefined="true" sourceSignal="pad_signal_Channel_P" targetSignal="Channel_P" required="false" srcVirtualSignal="//@virtualSignals.41" targetVirtualSignal="//@virtualSignals.15"/>
  <connections URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_pin_signal_q/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_q" systemDefined="true" sourceSignal="pad_signal_Channel_Q" targetSignal="Channel_Q" required="false" srcVirtualSignal="//@virtualSignals.42" targetVirtualSignal="//@virtualSignals.16"/>
  <connections URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_pin_signal_r/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_r" systemDefined="true" sourceSignal="pad_signal_Channel_R" targetSignal="Channel_R" required="false" srcVirtualSignal="//@virtualSignals.43" targetVirtualSignal="//@virtualSignals.17"/>
  <connections URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_pin_signal_s/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_s" systemDefined="true" sourceSignal="pad_signal_Channel_S" targetSignal="Channel_S" required="false" srcVirtualSignal="//@virtualSignals.44" targetVirtualSignal="//@virtualSignals.18"/>
  <connections URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_pin_signal_t/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_t" systemDefined="true" sourceSignal="pad_signal_Channel_T" targetSignal="Channel_T" required="false" srcVirtualSignal="//@virtualSignals.45" targetVirtualSignal="//@virtualSignals.19"/>
  <connections URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_pin_signal_u/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_u" systemDefined="true" sourceSignal="pad_signal_Channel_U" targetSignal="Channel_U" required="false" srcVirtualSignal="//@virtualSignals.46" targetVirtualSignal="//@virtualSignals.20"/>
  <connections URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_pin_signal_v/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_v" systemDefined="true" sourceSignal="pad_signal_Channel_V" targetSignal="Channel_V" required="false" srcVirtualSignal="//@virtualSignals.47" targetVirtualSignal="//@virtualSignals.21"/>
  <connections URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_pin_signal_w/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_w" systemDefined="true" sourceSignal="pad_signal_Channel_W" targetSignal="Channel_W" required="false" srcVirtualSignal="//@virtualSignals.48" targetVirtualSignal="//@virtualSignals.22"/>
  <connections URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_pin_signal_x/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_x" systemDefined="true" sourceSignal="pad_signal_Channel_X" targetSignal="Channel_X" required="false" srcVirtualSignal="//@virtualSignals.49" targetVirtualSignal="//@virtualSignals.23"/>
  <connections URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_pin_signal_y/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_y" systemDefined="true" sourceSignal="pad_signal_Channel_Y" targetSignal="Channel_Y" required="false" srcVirtualSignal="//@virtualSignals.50" targetVirtualSignal="//@virtualSignals.24"/>
  <connections URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_pin_signal_z/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_z" systemDefined="true" sourceSignal="pad_signal_Channel_Z" targetSignal="Channel_Z" required="false" srcVirtualSignal="//@virtualSignals.51" targetVirtualSignal="//@virtualSignals.25"/>
  <connections URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_a_analog_io_pin/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_a" systemDefined="true" sourceSignal="pin" targetSignal="Channel_A" targetVirtualSignal="//@virtualSignals.0" proxySrcVirtualSignalUri="http://resources/4.0.10/app/ANALOG_IO/0/vs_analog_io_pad_pin" containingProxySignal="true">
    <downwardMapList xsi:type="ResourceModel:VirtualSignal" href="../../ANALOG_IO/v4_0_10/ANALOG_IO_0.app#//@virtualSignals.0"/>
    <srcVirtualSignal href="../../ANALOG_IO/v4_0_10/ANALOG_IO_0.app#//@virtualSignals.0"/>
  </connections>
  <connections URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_b_analog_io_pin/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_b" systemDefined="true" sourceSignal="pin" targetSignal="Channel_B" targetVirtualSignal="//@virtualSignals.1" proxySrcVirtualSignalUri="http://resources/4.0.10/app/ANALOG_IO/1/vs_analog_io_pad_pin" containingProxySignal="true">
    <downwardMapList xsi:type="ResourceModel:VirtualSignal" href="../../ANALOG_IO/v4_0_10/ANALOG_IO_1.app#//@virtualSignals.0"/>
    <srcVirtualSignal href="../../ANALOG_IO/v4_0_10/ANALOG_IO_1.app#//@virtualSignals.0"/>
  </connections>
  <connections URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_c_analog_io_pin/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_c" systemDefined="true" targetSignal="Channel_C" required="false" targetVirtualSignal="//@virtualSignals.2" containingProxySignal="true"/>
  <connections URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_d_analog_io_pin/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_d" systemDefined="true" targetSignal="Channel_D" required="false" targetVirtualSignal="//@virtualSignals.3" containingProxySignal="true"/>
  <connections URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_e_analog_io_pin/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_e" systemDefined="true" targetSignal="Channel_E" required="false" targetVirtualSignal="//@virtualSignals.4" containingProxySignal="true"/>
  <connections URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_f_analog_io_pin/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_f" systemDefined="true" targetSignal="Channel_F" required="false" targetVirtualSignal="//@virtualSignals.5" containingProxySignal="true"/>
  <connections URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_g_analog_io_pin/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_g" systemDefined="true" targetSignal="Channel_G" required="false" targetVirtualSignal="//@virtualSignals.6" containingProxySignal="true"/>
  <connections URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_h_analog_io_pin/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_h" systemDefined="true" targetSignal="Channel_H" required="false" targetVirtualSignal="//@virtualSignals.7" containingProxySignal="true"/>
  <connections URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_i_analog_io_pin/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_i" systemDefined="true" targetSignal="Channel_I" required="false" targetVirtualSignal="//@virtualSignals.8" containingProxySignal="true"/>
  <connections URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_j_analog_io_pin/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_j" systemDefined="true" targetSignal="Channel_J" required="false" targetVirtualSignal="//@virtualSignals.9" containingProxySignal="true"/>
  <connections URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_k_analog_io_pin/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_k" systemDefined="true" targetSignal="Channel_K" required="false" targetVirtualSignal="//@virtualSignals.10" containingProxySignal="true"/>
  <connections URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_l_analog_io_pin/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_l" systemDefined="true" targetSignal="Channel_L" required="false" targetVirtualSignal="//@virtualSignals.11" containingProxySignal="true"/>
  <connections URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_m_analog_io_pin/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_m" systemDefined="true" targetSignal="Channel_M" required="false" targetVirtualSignal="//@virtualSignals.12" containingProxySignal="true"/>
  <connections URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_n_analog_io_pin/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_n" systemDefined="true" targetSignal="Channel_N" required="false" targetVirtualSignal="//@virtualSignals.13" containingProxySignal="true"/>
  <connections URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_o_analog_io_pin/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_o" systemDefined="true" targetSignal="Channel_O" required="false" targetVirtualSignal="//@virtualSignals.14" containingProxySignal="true"/>
  <connections URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_p_analog_io_pin/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_p" systemDefined="true" targetSignal="Channel_P" required="false" targetVirtualSignal="//@virtualSignals.15" containingProxySignal="true"/>
  <connections URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_q_analog_io_pin/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_q" systemDefined="true" targetSignal="Channel_Q" required="false" targetVirtualSignal="//@virtualSignals.16" containingProxySignal="true"/>
  <connections URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_r_analog_io_pin/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_r" systemDefined="true" targetSignal="Channel_R" required="false" targetVirtualSignal="//@virtualSignals.17" containingProxySignal="true"/>
  <connections URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_s_analog_io_pin/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_s" systemDefined="true" targetSignal="Channel_S" required="false" targetVirtualSignal="//@virtualSignals.18" containingProxySignal="true"/>
  <connections URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_t_analog_io_pin/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_t" systemDefined="true" targetSignal="Channel_T" required="false" targetVirtualSignal="//@virtualSignals.19" containingProxySignal="true"/>
  <connections URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_u_analog_io_pin/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_u" systemDefined="true" targetSignal="Channel_U" required="false" targetVirtualSignal="//@virtualSignals.20" containingProxySignal="true"/>
  <connections URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_v_analog_io_pin/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_v" systemDefined="true" targetSignal="Channel_V" required="false" targetVirtualSignal="//@virtualSignals.21" containingProxySignal="true"/>
  <connections URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_w_analog_io_pin/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_w" systemDefined="true" targetSignal="Channel_W" required="false" targetVirtualSignal="//@virtualSignals.22" containingProxySignal="true"/>
  <connections URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_x_analog_io_pin/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_x" systemDefined="true" targetSignal="Channel_X" required="false" targetVirtualSignal="//@virtualSignals.23" containingProxySignal="true"/>
  <connections URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_y_analog_io_pin/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_y" systemDefined="true" targetSignal="Channel_Y" required="false" targetVirtualSignal="//@virtualSignals.24" containingProxySignal="true"/>
  <connections URI="http://resources/4.1.22/app/ADC_MEASUREMENT/0/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_z_analog_io_pin/http://resources/4.1.22/app/ADC_MEASUREMENT/0/vs_adc_measurement_channel_z" systemDefined="true" targetSignal="Channel_Z" required="false" targetVirtualSignal="//@virtualSignals.25" containingProxySignal="true"/>
</ResourceModel:App>
